### ISSUE TITLE
Separate redis instances of shared-VM plan from the broker vm

### ISSUE THREAD

**Issue by bcshuai** [pivotal-cf/cf-redis-broker#2]
Hi,
Due to the broker api v1 will not be supported in future, I have been investigating a new replacement of the redis community service that supports the v2 api, and this repo is what I am looking for except some aspects. 

**# Scalability**
For now, as all the redis instances of shared-vm plan share the same vm with the redis broker,  I think it limits the scalability of both the broker and the numbers of redis instances, so why not separate those redis instances from the broker's vm, and put those redis instances into another vms?  Then it will also be convenient to scale out the broker, and add the number of shared vms to provision more redis instances.

**# Customization**
Because almost all the service catalog information has been hardcoded, it's impossible to customize the service catalog information, such as add some new service metadata values, or some new tags, unless I modify the source code of this repo. 

For now, this broker provides two kind of plan: shared-vm, and dedicated-vm.  Is there any working plan to support defining some new plans based on the max client connections and max memory?

**Comment by thereses** [comment]
Our near-term roadmap includes on demand provisioning of Redis instances, which will address the needs you describe above.

**Comment by thereses** [comment]
If you have specific configurations in mind, please share them here. Thanks.

**Comment by bcshuai** [comment]
That's a good news. For the scalability, I do have some ideas about how to seprate those redis instances from the broker's vm.

1. for each vm which will host the redis instances, there will be a agent running on it, and brokers communicate with these vms via http protocol,
and all these vms will be pre-defined in the configuration file of brokers.
2. for each provisioning request, or other instance management requests, the broker will talk to those known shared-vm agents, and choose the right one, then delegate the request to that agent, the agent will do the real job, then return the result to the broker.
3. A broker talks to the agents concurrently, not just one by one, and this can be done with goroutine, and those goroutine can be synchronized with waitgroup.

I have already written some code to implement this idea, and for now it seems to work fine. If you guys are interested in it, maybe I can issue a pull request, then you can konw what I am trying to do with more details.

**Comment by thereses** [comment]
Update: we don't have any current plans to add this to our roadmap. Thanks for the offer of a pr but as it isn't a feature we want to support we won't accept any contributions containing it.
